# Generated by Django 2.2.3 on 2019-08-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='segmentation_analysis',
            fields=[
                ('analysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='segmentation_app.analysis')),
            ],
            bases=('segmentation_app.analysis',),
        ),
    ]
